services:
  app:
    build:
      context: ./shop
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://user:password@postgres:5432/dbname?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    command: ["./main"]

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dbname"]
      interval: 5s
      retries: 5
      timeout: 3s

  migrator:
    build:
      context: ./migrator
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_SOURCE=postgresql://user:password@postgres:5432/dbname?sslmode=disable

volumes:
  postgres_data:
